### ISSUE TITLE
IndexError: The point point is outside data

### ISSUE THREAD

**Issue by soichih** [brain-life/app-dipy-tracking#2]
@aarya22 

My app-dipy-tracking failed with following issue.

```
gcc version 6.3.0 loaded.
Intel compiler suite version 17.0.3 loaded.
Python programming language version 2.7.13 loaded.
Python programming language version 2.7.13 unloaded.
Anaconda2.7 version 4.3.1 loaded.
FreeSurfer tools version 6.0.0 loaded.
/N/u/aryaam/Karst/github_repos/dipy/dipy/reconst/peaks.py:428: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  shm_coeff = np.zeros((shape + (n_shm_coeff,)))
/N/u/aryaam/Karst/github_repos/dipy/dipy/reconst/csdeconv.py:818: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  roi = data[ci - w: ci + w, cj - w: cj + w, ck - w: ck + w]
Traceback (most recent call last):
  File "/N/u/brlife/Carbonate/.sca/services/brain-life/app-dipy-tracking/main.py", line 116, in <module>
    main()
  File "/N/u/brlife/Carbonate/.sca/services/brain-life/app-dipy-tracking/main.py", line 95, in main
    streamlines = list(streamlines)
  File "/N/u/aryaam/Karst/github_repos/dipy/dipy/tracking/utils.py", line 898, in move_streamlines
    for sl in streamlines:
  File "/N/u/aryaam/Karst/github_repos/dipy/dipy/tracking/local/localtracking.py", line 108, in _generate_streamlines
    directions = dg.initial_direction(s)
  File "/N/u/aryaam/Karst/github_repos/dipy/dipy/direction/probabilistic_direction_getter.py", line 215, in initial_direction
    pmf = self.pmf_gen.get_pmf(point)
  File "/N/u/aryaam/Karst/github_repos/dipy/dipy/direction/probabilistic_direction_getter.py", line 45, in get_pmf
    coeff = trilinear_interpolate4d(self.shcoeff, point)
  File "dipy/tracking/local/interpolation.pyx", line 72, in dipy.tracking.local.interpolation.trilinear_interpolate4d (dipy/tracking/local/interpolation.c:2878)
  File "dipy/tracking/local/interpolation.pyx", line 105, in dipy.tracking.local.interpolation.trilinear_interpolate4d (dipy/tracking/local/interpolation.c:2655)
IndexError: The point point is outside data

real	7m53.445s
user	52m17.364s
sys	1m56.319s
```

The data that I am passing seems to be OK.. Can you take a look? I've created the .tar.gz of the app and data that's failed here
> /N/dc2/projects/lifebid/hayashis/tmp/issue1.tar

P.S.
I am running this to generate the test data we need for app-AFQ-seg. I just realized that all of our tracking app runs on single shell (dtiinit output dwi) so, for app-AFQ-seg, output from app-dipy-tracking would be the only valid output that we can use along with the original dwi input file.

**Comment by aarya22** [comment]
The problem here is that the app is using an older version of dipy that I was using for a different application. I will update the submit.pbs and it should fix.

**Comment by aarya22** [comment]
I've changed it, and I am now testing it on brain-life

**Comment by aarya22** [comment]
Never mind that did not fix the problem, I will ask the dipy community

**Comment by soichih** [comment]
OK

**Comment by chiaramff** [comment]
Hi! did u solve this issue? I get the same error, and I ve just updated dipy
Thanks!
